### PR TITLE
Update wechat sdk to latest version and add miniapp share api

### PR DESCRIPTION
**Pull request by LittoCats**

### CODE REVIEW

**Comment by jeffy7** [comment]
希望能尽早更新到最新的SDK

**Comment by hbk671104** [comment]
This feature is desperately needed, please merge ASAP.

**Comment by chaelaugh** [comment]
@LittoCats 您好 请问怎么分享小程序呢

**Comment by chaelaugh** [comment]
@LittoCats 请问分享小程序 android端可用吗

**Pull request closed without merging**
